### ISSUE TITLE
Running on Windows causes exception

### ISSUE THREAD

**Issue by sparkofreason** [seancorfield/depstar#8]
Here is the project to repro:

[https://github.com/sparkofreason/depstar-test](https://github.com/sparkofreason/depstar-test)

This is the error:
```
PS C:\Users\dave\Projects\uberjar-test> clojure -A:uberjar
{:warning "clashing jar item", :path "edu/emory/mathcs/utils/ConcurrencyUtils$CustomExceptionHandler.class", :strategy :noop}
{:warning "clashing jar item", :path "edu/emory/mathcs/utils/ConcurrencyUtils$CustomThreadFactory.class", :strategy :noop}
{:warning "clashing jar item", :path "edu/emory/mathcs/utils/ConcurrencyUtils.class", :strategy :noop}
Exception in thread "main" java.nio.file.NoSuchFileException: C:\Users\dave\AppData\Local\Temp\uberjar16821059387554463855\uncomplicate\neanderthal\aux.clj
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:231)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at java.base/java.nio.file.Files.copy(Files.java:3066)
        at hf.depstar.uberjar$copy_BANG_.invokeStatic(uberjar.clj:92)
        at hf.depstar.uberjar$copy_BANG_.doInvoke(uberjar.clj:85)
        at clojure.lang.RestFn.invoke(RestFn.java:467)
        at hf.depstar.uberjar$eval190$fn__191$fn__192.invoke(uberjar.clj:141)
        at hf.depstar.uberjar$consume_jar.invokeStatic(uberjar.clj:106)
        at hf.depstar.uberjar$consume_jar.invoke(uberjar.clj:98)
        at hf.depstar.uberjar$eval190$fn__191.invoke(uberjar.clj:133)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at hf.depstar.uberjar$copy_source.invokeStatic(uberjar.clj:174)
        at hf.depstar.uberjar$copy_source.invoke(uberjar.clj:172)
        at hf.depstar.uberjar$run$fn__224$fn__225.invoke(uberjar.clj:229)
        at clojure.core$run_BANG_$fn__8775.invoke(core.clj:7715)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6827)
        at clojure.core$run_BANG_.invokeStatic(core.clj:7710)
        at clojure.core$run_BANG_.invoke(core.clj:7710)
        at hf.depstar.uberjar$run$fn__224.invoke(uberjar.clj:229)
        at hf.depstar.uberjar$run.invokeStatic(uberjar.clj:228)
        at hf.depstar.uberjar$run.invoke(uberjar.clj:224)
        at hf.depstar.uberjar$_main.invokeStatic(uberjar.clj:235)
        at hf.depstar.uberjar$_main.invoke(uberjar.clj:233)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.main$main_opt.invokeStatic(main.clj:491)
        at clojure.main$main_opt.invoke(main.clj:487)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
```

**Comment by seancorfield** [comment]
The GitHub repo it refers to seems to be private so I cannot repro from that. Can you create a repro case that is _public_?

**Comment by sparkofreason** [comment]
It is public. I can access it from a browser that is not logged in to Github, only option in settings is to make it private.

**Comment by seancorfield** [comment]
ComputeSoftware/math -- the repo it refers to -- is private.

**Comment by sparkofreason** [comment]
Sorry about that, picked the wrong math library. Fixed and pushed.

**Comment by sparkofreason** [comment]
Minimized deps further to only include neanderthal, which still causes the issue. Also, the error does not occur when running `clojure -A:uberjar` under WSL.

**Comment by seancorfield** [comment]
Definitely seems to be something about neanderthal and only happens on Windows natively (PowerShell). It works fine on Mac and WSL. I can repro, and I've looked at it all with a debug version of depstar but right now I have no idea what might be causing it.

**Comment by seancorfield** [comment]
This fails because `aux.*` is a reserved filename on Windows and cannot be copied to the filesystem. Other filenames that are reserved include `con.*`, `prn.*`, `nul.*`, and several other "device"-like names.

For now, I've made the experience look like this:
```
PS C:\Users\sean\clojure\depstar-test> clj -A:uberjar
{:warning "could not find classpath entry", :path "resources"}
{:error "unable to copy file", :name "uncomplicate/neanderthal/aux.clj", :exception java.nio.file.NoSuchFileException, :message "C:\\Users\\sean\\AppData\\Local\\Temp\\uberjar6023424070156450310\\uncomplicate\\neanderthal\\aux.clj"}
Writing uber jar: test.jar

Completed with errors!
```
In theory, there are ways to workaround these reserved names by using a special path prefix (of either `\\.\` or `\\?\`) but it is not clear how to persuade Java's NIO file library to accept these.

I'll leave this open for now.

**Comment by sparkofreason** [comment]
I was able to "fix" using an in-memory file system, https://github.com/google/jimfs. Worked on the specific example (and was very fast), haven't tested yet on other platforms, though I think it should work. Holding off on making a PR until further testing, probably should discuss if this should be the only behavior, or an option vs. using a tmp folder on disk. See `{sparkofreason/depstar {:git/url "https://github.com/sparkofreason/depstar.git" :sha "1003f8cdd2d4a4ef5c39214086ae0c3d0db6ccf7"}`.

**Comment by sparkofreason** [comment]
Spoke too soon, only "works" in the sense of not throwing that exception, but the jar file is garbled because it used "\" instead of "/". Will try to fix that.

**Comment by seancorfield** [comment]
I modified `depstar` locally to use either the disk approach or the memory approach based on an env var for testing. On both Windows (PowerShell) and Mac, I get an identical JAR file -- I'm not seeing the "garbled" issue you mention.

However, there is a bigger issue with using Google's in-memory FS is that all those transitive dependencies end up in the JAR file which is a deal-breaker. We can't risk just filtering that out, since some of the transitive deps are likely to be used in real programs.

**Comment by sparkofreason** [comment]
Were you able to execute `java -cp test.jar clojure.main` on Windows? If I don't explicitly change the file separators, it won't find `clojure.main`. 

The transitive dependencies issue is definitely gross. I don't know how you'd fix that using deps. Seems like you'd need to construct the desired CP based on explicit aliases passed in via another command-line option.

**Comment by sparkofreason** [comment]
BTW, I tried using the Windows namespace prefix `"\\?\"`, but the Java API won't allow it. Interestingly, `sun.nio.fs.WindowsPath` uses it internally, but only when the path length is > 247 characters.

**Comment by sparkofreason** [comment]
I don't think the issue I saw running `clojure -cp ...` had to do with path separators per se, or if it did it was somehow conflated with using jimfs. Running directly from your latest still fails to find `clojure.main` in the uberjar. Some leaky abstraction in the Java file APIs on Windows or something. I even tried this on a project with no deps, just clojure.
