### ISSUE TITLE
NoSuchFileException upgrading from 0.1.7 to 0.2.0

### ISSUE THREAD

**Issue by jarohen** [seancorfield/depstar#9]
Hey Sean,

We're getting a `java.nio.file.NoSuchFileException: /tmp/depstar6800417798843186518/dist/catalogue.jar` upgrading from 0.1.7 to 0.2.0 - calling with main-opts `["-m" "hf.depstar.uberjar" "dist/catalogue.jar"]`. My guess would be that it's not creating parent directories, or something similar?

Stack trace:
```
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:116)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at hf.depstar.uberjar$run.invokeStatic(uberjar.clj:228)
	at hf.depstar.uberjar$run.invoke(uberjar.clj:218)
	at hf.depstar.uberjar$_main.invokeStatic(uberjar.clj:243)
	at hf.depstar.uberjar$_main.invoke(uberjar.clj:241)
```

Will have a dig if I get a spare 10 mins or so.

Cheers,

James

**Comment by seancorfield** [comment]
Ah, a use case I had not considered! Thanks for the PR. Reviewing that next.

**Comment by seancorfield** [comment]
Fixed in 0.2.1 release.

**Comment by jarohen** [comment]
awesome, cheers!

**Comment by seancorfield** [comment]
The PR does not actually solve the problem. It creates the parent folder in the temp directory, but not when it is copied to the final resting place. Reopening this so I can add the same logic prior to the copy.

**Comment by jarohen** [comment]
Aha - yes, we didn't run into that because the directory was already created. Can add the same behaviour before the `Files/move` call [here](https://github.com/seancorfield/depstar/blob/5bae6a7aa864aff797e2af418aee16f2b4b58a36/src/hf/depstar/uberjar.clj#L236)?

**Comment by seancorfield** [comment]
Yup, it needs to wrap `(path dest)` to call `mkdirs` on its parent.
